name: "Feature request"
description: "Suggest an idea to improve the project"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion!
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe what you'd like to happen
      validations:
        required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
  - type: checkboxes
    id: checks
    attributes:
      label: Validations
      options:
        - label: I have searched existing issues
          required: true
