name: Pull Request Labeler
on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: labeler-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  triage:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
