name: Release Drafter
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
