name: Repository hygiene

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli2
        run: npm i -g markdownlint-cli2

      - name: Run markdownlint
        run: markdownlint-cli2 "**/*.md" "#**/node_modules/**"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install codespell
        run: python -m pip install --upgrade pip && pip install codespell

      - name: Run codespell
        run: codespell

      - name: Link checker (lychee)
        uses: lycheeverse/lychee-action@v2
        with:
          args: --max-redirects 8 --retry-wait-time 2 --accept 200,204,206,301,302,307,308 --exclude-mail --no-progress './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: actionlint
        uses: raven-actions/actionlint@v2

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v4
        with:
          config_file: .yamllint.yml
