name: OpenSSF Scorecards

on:
  branch_protection_rule:
  schedule:
    - cron: '0 3 * * 1'
  push:
    branches: [ "**" ]

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: scorecards-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
