name: Semantic PR
on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

concurrency:
  group: semantic-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    if: github.event.pull_request.draft == false
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
