name: Semgrep SAST
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '0 5 * * 1'

permissions:
  contents: read
  security-events: write

concurrency:
  group: semgrep-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/javascript
            p/python
            p/golang
          generateSarif: true
